import random

import torch.nn as nn

from .alexBeth import AlexBeth
from ..agents import Asker, Retriever
from ..utils.misc import build_optimizer


# Parses a "x-y" string into an (x, y) pair of ints; None yields `default`.
def _parse_pair(spec, default):
    if(spec is None):
        return default
    parts = str(spec).split("-")
    assert (len(parts) == 2), f"expected a pair in the form 'x-y', got {spec!r}"
    return (int(parts[0]), int(parts[1]))


# Population variant of AlexBeth. There are `n` askers (Alex·es) and `m` retrievers (Beth·s),
# set by `pop_size` ("n-m"). For each training round a random asker and a random retriever are
# selected and trained together; a single optimizer covers the whole population, so only the
# parameters of the selected pair (the ones receiving gradients) are updated by a step.
#
# Agents are periodically reinitialized ("rejuvenated"), set by `pop_reset_period` ("a-b"):
# askers every `a` epochs and retrievers every `b` epochs (0 means never). Within a group the
# resets are staggered so that they are spread over the period rather than happening together:
# with `n` askers and period `a`, one asker is reinitialized roughly every `a/n` epochs, so no
# asker ever lives more than `a` epochs (and likewise for retrievers).
#
# During evaluation, the language is generated by the *oldest* asker (the one that has been
# training the longest since its last reset), so the evaluated language is stable and mature.
#
# Equivalences:
#   * AlexBeth                      == AlexBethPopulation(pop_size=1-1, pop_reset_period=0-0)
#   * AlexBeth + old "beth reaper"  == AlexBethPopulation(pop_size=1-1, pop_reset_period=0-B)
class AlexBethPopulation(AlexBeth):
    def __init__(self, args, logger, dataset, signal_dump_dir):
        # Build all the standard AlexBeth state (config, eval buffers, curriculum, negation
        # correspondence, ...). This also creates a single throwaway asker/retriever and
        # optimizer, which we immediately replace below with the populations.
        super().__init__(args, logger, dataset, signal_dump_dir)

        if(self.shared):
            raise NotImplementedError("AlexBethPopulation does not support shared parameters.")

        self.n_askers, self.m_retrievers = _parse_pair(getattr(args, "pop_size", None), (2, 2))
        self.asker_period, self.retriever_period = _parse_pair(getattr(args, "pop_reset_period", None), (0, 0))
        assert (self.n_askers >= 1) and (self.m_retrievers >= 1), "pop_size must be at least 1-1"
        assert (self.asker_period >= 0) and (self.retriever_period >= 0), "pop_reset_period must be at least 0-0"

        askers = [Asker.from_args(args) for _ in range(self.n_askers)]
        retrievers = [Retriever.from_args(args) for _ in range(self.m_retrievers)]
        self._askers = nn.ModuleList(askers)
        self._retrievers = nn.ModuleList(retrievers)
        self._agents = nn.ModuleList(askers + retrievers)

        # One optimizer over the whole population. For a given batch only the selected asker and
        # retriever receive gradients, so a single optimizer step updates just them (Adam skips
        # parameters whose `.grad` is None).
        self._optim = build_optimizer(self._agents.parameters(), args.learning_rate)

        # Staggered reinitialization schedule. We track, per agent, the epoch of its last
        # (re)initialization (`birth`), and reinitialize an agent once its age (epochs since
        # birth) reaches the period. Agents are pre-aged with staggered offsets (encoded as
        # negative births) so that agent i of a group of `count` with period `p` starts at age
        # floor(i * p / count); its first reset then happens at epoch p - floor(i*p/count).
        # Hence the group's first reset occurs at ~p/count and every agent's lifespan is <= p.
        self._asker_birth = self._initial_births(self.n_askers, self.asker_period)
        self._retriever_birth = self._initial_births(self.m_retrievers, self.retriever_period)
        self._current_epoch = 0

        # A concrete pair must always be set; start_episode() overwrites this before every round.
        self._asker = self._askers[0]
        self._retriever = self._retrievers[0]

    # birth = -offset, so that age(epoch) = epoch - birth = epoch + offset.
    @staticmethod
    def _initial_births(count, period):
        if(period <= 0):
            return [0] * count
        return [-((i * period) // count) for i in range(count)]

    @property
    def all_agents(self):
        return self._agents

    @property
    def current_agents(self):
        return (self._asker, self._retriever)

    # The oldest asker = the one with the largest age = the smallest birth epoch (ties: lowest
    # index). Used to fix the language during evaluation.
    def _oldest_asker(self):
        i = min(range(self.n_askers), key=(lambda j: self._asker_birth[j]))
        return self._askers[i]

    # Overrides Game.start_episode: select the agents used for this round.
    # Training: a random asker and a random retriever. Evaluation: the oldest asker (stable,
    # well-trained language) and a random retriever.
    def start_episode(self, train_episode=True):
        self._asker = random.choice(self._askers) if train_episode else self._oldest_asker()
        self._retriever = random.choice(self._retrievers)

        super().start_episode(train_episode=train_episode)  # sets train/eval mode on current_agents

    # Overrides Game.start_epoch: apply the reinitialization schedule.
    def start_epoch(self, data_iterator, summary_writer):
        super().start_epoch(data_iterator, summary_writer)  # sets train mode

        self._reinit_due(self._askers, self._asker_birth, self.asker_period, self._current_epoch, "asker")
        self._reinit_due(self._retrievers, self._retriever_birth, self.retriever_period, self._current_epoch, "retriever")

        self._current_epoch += 1

    # Reinitializes every agent of a group whose age has reached `period` (0 = never), and
    # clears the corresponding optimizer state (stale Adam moments).
    def _reinit_due(self, agents, births, period, epoch, kind):
        if(period <= 0):
            return
        for i, agent in enumerate(agents):
            if((epoch - births[i]) >= period):
                agent.reinitialize()
                for p in agent.parameters():
                    self._optim.state.pop(p, None)
                births[i] = epoch
                print(f"[pop-reset] epoch {epoch}: {kind} {i} reinitialized.")
